echo "zz autogenerated by $0, probably don't edit by hand" > exercises.dz
awk -f gen_problems.awk problems.txt >> exercises.dz
awk -f gen_curated.awk curated.txt >> exercises.dz
echo "created exercises.dz"
